name: 'Secret Scanning Review Test branch'
on: [pull_request]

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@v2.0.0
        with:
          token: ${{ secrets.akhil-gh-fga-token }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python'