name: 'Secret Scanning Review'
on:
  workflow_dispatch:
    inputs:
      deploy_to_live:
        description: 'Deploy to live'
        type: boolean
        default: false
        required: true
  push:
    branches:
      - main

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    if: ( github.ref_name == 'main' || github.event.inputs.deploy_to_live == 'true')
    steps:
      - name: 'step1'
        run: |
          echo 'Hi'
          echo "output: ${{ github.ref_name }}, ${{ github.event.inputs.deploy_to_live }}"
      - name: 'step2'
        run: |
          echo 'Hey'
