name: 'Secret Scanning Review'
on: [pull_request]

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check python version'
        run: | 
          python --version
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@v2.1.0
        id: secret-alert-check
        with:
          token: ${{ secrets.SCAN_TOKEN }}
          runtime: 'python'
          fail-on-alert-exclude-closed: true
          fail-on-alert: true
      - name: 'Log alert metadata'
        if: always()
        run: |
          echo 'Failed'
          echo ${{ env.GITHUB_STEP_SUMMARY }}