name: 'Secret Scanning Review'
on: [pull_request]

jobs:
  secret-scanning-review:
    # runs-on: codebuild-akhil-codebuild-project-${{ github.run_id }}-${{ github.run_attempt }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Check python version'
        run: | 
          python --version
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@v2.1.0
        id: secret-alert-check
        with:
          token: ${{ secrets.SCAN_TOKEN }}
          runtime: 'python'
      - name: 'Log alert metadata'
        run: |
          echo ${{ steps.secret-alert-check.outputs.GITHUB_STEP_SUMMARYs }}
          echo ${{ steps.secret-alert-check.outputs.alerts }}