name: 'Secret Scanning Review'
on: [pull_request]

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@v2.1.0
        id: secret-alert-check
        with:
          token: ${{ secrets.SCAN_TOKEN }}
          fail-on-alert: false
          fail-on-alert-exclude-closed: true
          runtime: 'python'
      - name: 'Log alert metadata'
        if: always()
        run: |
          echo ${{ steps.secret-alert-check.outputs.alerts }}