name: A nice git workflow
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]

jobs:
  Job1-workflow2:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "This is step One"
      - name: Step Two
        run: echo "This is step Tw0"
      - name: Step Two
        run: echo "This is step Tw0"